### ISSUE TITLE
cannot properly select true/false member for Boolean levels?

### ISSUE THREAD

**Issue by jspeis** [Datawheel/mondrian-rest-ui#20]
Not sure if this is just an issue with my config, but I notice with this simple Dimension:

```
  <Dimension name="Workforce Status">
    <Hierarchy hasAll="true">
      <Level column="in_workforce" name="Workforce Status" type="Boolean" uniqueMembers="true"/>
    </Hierarchy>
  </Dimension>
```

When I try to do a cut on Workforce Status and when I try to click `true` it automatically gets unclicked and so I can't cut on this from the GUI

<img width="937" alt="screen shot 2018-03-06 at 1 20 11 pm" src="https://user-images.githubusercontent.com/87581/37050187-317c335a-2141-11e8-81ab-b226cdbc9a76.png">

Drilldowns appear to work fine

**Comment by jspeis** [comment]
@frabarz would you be able to take a look into this whenever you happen to have a chance? (as an example you can see the "Workforce Status" dimension in the `pums_1` cube?)

**Comment by frabarz** [comment]
Sorry! I didn't see it. This PR fixes it.
