### ISSUE TITLE
when sorting table some values at end of list disappear

### ISSUE THREAD

**Issue by jspeis** [Datawheel/mondrian-rest-ui#26]
For example if you go to:

https://canon-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJTdGF0ZSIsIlN0YXRlIl1dLCJjdXRzIjpbW1syMDEyXSxbIlllYXIiLCJZZWFyIiwiWWVhciJdXV0sImN1YmUiOiJoZWFsdGhfZGVhdGhzX3Blcl8xMDAwX2FkdWx0X2hvc3BpdGFsX2FkbWlzc2lvbnNfd2l0aF9wbmV1bW9uaWEiLCJtZWFzdXJlcyI6WyJEZWF0aHMgUGVyIDEsMDAwIEFkdWx0IEhvc3BpdGFsIEFkbWlzc2lvbnMgV2l0aCBQbmV1bW9uaWEiXX0=

You will see both Alaska and Arizona in the list. But if you start to sort the data by "Deaths Per 1,000 Adult Hospital Admissions With Pneumonia" you'll notice that when the list is Ascending, Alaska disappears and when the list is descending Arizona dispeears.

**Comment by jspeis** [comment]
@frabarz would you be able to look into this?

**Comment by frabarz** [comment]
sorry for the lateness!
a335b5c5926c16a6606e8348cc74ab4c15c65206 solves both issues

**Comment by jspeis** [comment]
great, thanks!
