### ISSUE TITLE
cutting on TimeMonths levels do not appear to work as expected

### ISSUE THREAD

**Issue by jspeis** [Datawheel/mondrian-rest-ui#28]
cuts on the month dimension don't work in the mondrian-rest-ui/mondrian-rest-client for the `casen_banking` cube, for instance

 https://chilecube.datawheel.us/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJHZW9ncmFwaHkiLCJDb211bmEiXV0sImN1dHMiOltdLCJjdWJlIjoiY2FzZW5fYmFua2luZyIsIm1lYXN1cmVzIjpbIk51bWJlciBvZiByZWNvcmRzIl19 ... I noticed a similar issue in Data USA's spending cube

**Comment by frabarz** [comment]
This is an issue of `mondrian-rest`.
