### ISSUE TITLE
incorrect logic layer URL cuts

### ISSUE THREAD

**Issue by davelandry** [Datawheel/mondrian-rest-ui#29]
When constructing the logic layer URL, we are using the member names for cuts, not IDs.

For example, in the Data USA API, to cut on the state of Massachusetts the query is `State=04000US25` and not `State=Massachusetts`

**Comment by cnavarreteliz** [comment]
closed via [0c1b563](https://github.com/Datawheel/mondrian-rest-ui/commit/0c1b563ef5aea3aa1cba68ab303c3abfd327b903)

cc: @davelandry
